# Generated by Django 6.0.3 on 2026-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='forks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
