# Generated by Django 6.0.3 on 2026-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repository_forks_count_repository_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
