# Generated by Django 6.0.3 on 2026-04-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(max_length=255, unique=True)),
                ('ai_summary', models.TextField()),
                ('top_languages', models.JSONField(default=dict)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('key_achievements', models.JSONField(default=list)),
                ('suggested_tags', models.JSONField(default=list)),
                ('ai_model_used', models.CharField(default='gemini-pro', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='repositories.repository')),
            ],
        ),
    ]
