# Generated by Django 6.0.3 on 2026-04-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInsight',
            new_name='Insight',
        ),
    ]
